version: "2"

networks:
  app-tier:
    driver: bridge

services:
  zookeeperQ:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-tier
  kafkaQ:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeperQ:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - app-tier
    depends_on:
      - zookeeperQ
  nestapp:
    container_name: micro-nest
    build:
      context: ./micro-nest
      target: development
      dockerfile: Dockerfile
    command: tail -f /dev/null
    networks:
      - app-tier
    volumes:
      - ./micro-nest:/usr/src/app
      - ./micro-nest/node_modules:/usr/src/app/node_modules
    restart: unless-stopped

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
